### ISSUE TITLE
downmix, support, root, compile etc....

### ISSUE THREAD

**Issue by mycop5** [lgstreamer/dts_restore#3] opened 2023-04-28 11:54 UTC
Hi! 
1. This script will work at Nano Series? 
2. This script only work with webos 5? what about 3, 4... or 6?
3. Can you please detaily explain what exactly yuor script does?
As i understand? you override lib by mount you own "patched" version?
4. If it so... Then please explain why it need to downmix? its OK for stereo TV speakers.  But is importantet to make Bitstream pastroug over HdmiARC or SPDIF. As i understand script pass of software player limitation. So how to disable downmix in this case and set audio stream as is? Cuz is much importances than just play stereo.
5. Why only MKV supported?
6. It is possible make support for another File System support. Like EXFAT for example?  It actualy strange... this OS is Lunux based. hovewer native kinux filse system like ext2-4 not supported! i mean...you can mount it directly...but Player cannot open this drive.
7. Why just cant take video player from previos version of webos and make ssame script trick?
I mean... some TV mode of 2020-2019 have same hardware part. And minor changes. even LG support confirm it.
8. What if flash 2019 firmware  to 2020 tv? (with same hardware of course)
9. As i understand You haveToolcahni to compile Firmware for TV. What if compile custom firmware. will it work?

**Comment by pbatard** [comment] 2023-04-28 12:50
1. No idea. Only LG CX are supported.
2. No idea. Only webOS 5 is supported.
3. It restores the DTS decoding for MKV that has been removed by LG by enabling DTS downmix to stereo. It does nothing else. Especially it does not provide DTS bypass or anything.
4. Explained in "What about the limitations" [here](https://github.com/RootMyTV/RootMyTV.github.io/issues/72#issuecomment-1343204028). Figuring out bitstream passthrough would most likely require **months** of disassembling and reverse engineering LG's proprietary libraries, and, because it involves specific hardware calls, would most likely be limited to a specific model. **I don't have the time to do that, so if that's what you want, you'll have to find somebody else to do it**.
5. Because that's all I need.
6. This is outside of the scope of what this is about. This is about restoring DTS playback from MKV, not customising the firmware. It's not because we are doing one thing here that we are even remotely interested in the other.
7. This has been tried. It doesn't work. And also it would be illegal to publish the video player binaries, as some of them are proprietary and copyrighted by LG. And these are only minor changes if you have full access to the hardware specs and the proprietary hardware library sources, which **only** LG has.
8. Out of scope.
9. Nobody but LG can create a firmware that will be accepted by your TV, as the firmware images are digitally signed so, even if you were to build your own firmware, you wouldn't be able to sign it so that you can use the firmware update utility. And also, because there are A LOT of libraries in the firmware that are proprietary and for which LG does not publish the source, even if you have a toolchain, you can't recompile a firmware that can work as a replacement, as you will be missing too many elements that are required for the firmware to work and for which you don't have the source.

The best thing I can advise you here is to please stop believing that there exists a _simple_ solution to whatever you want to accomplish. Please invest your own time to look into this, and once you have done that, you will both be able to answer all the questions above on your own as well as realise that the reason because the current solution only goes as far as it goes and may look very limited with regards to what you'd like, is because it's a lot more complex to accomplish anything than you realise.

**Closed as completed by pbatard** 2023-04-28 12:50 UTC

**Comment by aabytt** [comment] 2023-04-28 13:08
1. Depends on socket, I can confirm it works on CX/C1/C2, Nano 796 (webos 5) 
2. webos 1.0-4.9 support DTS, no need for a patch

**Comment by mycop5** [comment] 2023-04-28 15:12
> 4\. **I don't have the time to do that, so if that's what you want, you'll have to find somebody else to do it**.

You heve very strange agressive...position...IMHO....
No one beg you make some you dont want.
No one tell that its easy.
I ask it here, (mix) cuz  neither you dont provide feedback, and  many peoples may have same questions. Nor, even not provide "details" but public it on thitd party "git" , not you own.. so... why you surprise this questions? and why "close" issue so fast?

This questions exactly coz someday in this or next year i may get access to TV 2020 wich same as 2019 and thats why i  preventive asked about tryin to override video player.  You tryed it. But again... "This has been tried. It doesn't work.. "
No one ask you to public "binary"!
what exactly been trying?
Wich firmware version and tv, you use as base? 
You extract firmware or take from source and compile by your own?
Just more than two word, please, about success and fail. 

> 1. Depends on socket, I can confirm it works on CX/C1/C2, Nano 796 (webos 5)

thanks.

> 2\. webos 1.0-4.9 support DTS, no need for a patch

its question not for dts patch but for compatibility.

**Comment by pbatard** [comment] 2023-04-28 15:51
>  you dont provide feedback

The feedback has already been provided in the issue that is pointed out explicitly in the readme. I will assert that if you had looked at it, you would have found that most of your questions had already been answered. The readme literally says:

> See https://github.com/RootMyTV/RootMyTV.github.io/issues/72 for details.

My problem is that you appear not have bothered to perform your own research by simply having a look at the readme and looking at the link above. That issue also answers your question about the Nano and your subsequent questions about what firmware I have been using or what's been tried. So, yeah, don't feel surprised if people are less than sympathetic to answer your request when it is pretty clear you haven't really looked at the one place where you had been told to look if you wanted to find out more.

**Comment by mycop5** [comment] 2023-04-28 16:04
Touché...  =)
You post  on another "git"....
I missed this link... (actualy dont know how it exactly happen... i learn it two days)

**Comment by davix004** [comment] 2023-05-08 11:10
> Hi!
> 
> 1. This script will work at Nano Series?
> 2. This script only work with webos 5? what about 3, 4... or 6?

Hello,
As I stated [here](https://github.com/RootMyTV/RootMyTV.github.io/issues/72#issuecomment-1386899512), this script works in the 43NANO766QA 2022 model, that I own, with webos 7 version. So i suppose that it works in all Nano series with that webos version. As pbatard mention, you have to read all the post and readme before asking already answered questions.

**Comment by tedetorry** [comment] 2023-10-04 16:09
Tried every step succesfully on an LG 50UQ8050PSB and I can choose the DTS track and I dont get the "audio not supported" but I can`t listen to it. It sounds as if you were punched in the face and lost hearring. Some heavy noises like drumbs or punches sound very weird.
