### ISSUE TITLE
Error while installing override from telnet

### ISSUE THREAD

**Issue by kshpits** [lgstreamer/dts_restore#2] opened 2023-02-13 15:35 UTC
Hello, i'm having an error on insatlling override section. Can you help?

```
This installer was designed specifically for LG OLED CX TVs running
webOS 5.x with Gstreamer 1.14.4. However, you are trying run it on a(n)
OLED-A55 TV with webOS 7.3.0 and GStreamer 1.18.2.

While installing this software on an incompatible platform should not
cause irreversible damage, if you choose to proceed, you do acknowlegde
that, because you are not using the relevant target system:
1. The software may not work as expected, it at all.
2. You may lose existing features and/or functionality.
3. The entire responsibility for trying this software on an unsupported
   platform lies entirely with you.

Do you wish to proceed? [y/N] y
Installing /var/lib/webosbrew/init.d/restore_dts
Running /var/lib/webosbrew/init.d/restore_dts
Installing /usr/lib/gstreamer-1.0/libgstmatroska.so override
Installing /usr/lib/gstreamer-1.0/libgstlibav.so override
Installing  override
>> [gst.tracer][INFO ][default] [ 5255][ 0x2018020] cooltracer registered
mount: /tmp/gst_1_0_registry.arm.bin: mount(2) system call failed: No such file or directory.
Installing /etc/gst/gstcool.conf override
DTS playback has been permanently re-enabled - Enjoy!
```

DTS not working after patch

**Comment by pbatard** [comment] 2023-02-13 16:24
> `This installer was designed specifically for LG OLED CX TVs running webOS 5.x with Gstreamer 1.14.4. However, you are trying run it on a(n) OLED-A55 TV with webOS 7.3.0 and GStreamer 1.18.2.`

I'm afraid it's going to be difficult for me to try to support non CX models, and especially ones that run much more recent versions of webOS and GStreamer.

From what I can see, the issue is that the global environmental variable `$GST_REGISTRY_1_0` that should be pointing to the GStreamer registry doesn't exist in your environment, and the script should have aborted on detecting that, but the condition that should have aborted installation is missing a statement. I will make sure to fix that, but of course that won't resolve your issue.

Most likely, you will have to wait until someone with an `A` model, or a model that has the registry that isn't defined with `$GST_REGISTRY_1_0` to come along and figure out how the GStreamer chain is installed in newer webOS.

Or you can try posting the output of the `set` command from a shell running on your model, to see if there's any variable that looks like a GStreamer registry path, but I really can't promise anything, as the chances are that if your model doesn't use `$GST_REGISTRY_1_0`, then the changes needed to re-enable DTS will be too different from the ones on CX.

**Comment by kshpits** [comment] 2023-02-13 16:27
Yes, there is no GST_REGISTRY_1_0  variable

```
HOSTNAME='LGwebOSTV'
IFS='
'
LD_PRELOAD=''
LINENO=''
OPTIND='1'
PATH='/sbin:/usr/sbin:/bin:/usr/bin'
PPID='3687'
PS1='\w \$ '
PS2='> '
PS4='+ '
PWD='/home/root'
SHLVL='3'
```

**Comment by pbatard** [comment] 2023-02-13 16:31
Your variable list looks awfully empty compared to mine:
```
[root@LGwebOSTV ~]# set
APPFRWK_MASK_PATH='/mnt/lg/cmn_data/appfrwk_mask'
ATTR_FORCE_SCHEDNORMAL='YES'
COMPONENTS_PATH='/mnt/lg/res/lglib/openmax'
CRASH_REPORT='YES'
DBGFRWK_SYSLOG='GLOBAL'
DEBUG_STATUS='3'
DEFAULT_WORKINGSET='20480'
DELAYLOGIN='no'
DMALLOC_OPTIONS='debug=0x34f47d83,inter=100,log=logfile'
EDITMOTD='no'
EDITOR='/bin/vi'
ENABLE_ROOTFS_FSCK='no'
FSCKFIX='yes'
GDB_ROOT='$'"'"'$HOME'"'"
GIO_EXTRA_MODULES='/usr/lib/gio/modules'
GLIBC_BACKTRACE='YES'
GST_PLUGIN_PATH='/usr/lib/gstreamer-0.10'
GST_PLUGIN_PATH_1_0='/usr/lib/gstreamer-1.0:/mnt/lg/res/lglib/gstreamer-1.0'
GST_PLUGIN_SCANNER='/usr/bin/gst-plugin-scanner'
GST_PLUGIN_SCANNER_1_0='/usr/libexec/gstreamer-1.0/gst-plugin-scanner'
GST_REGISTRY='/mnt/flash/data/gst_registry.arm.bin'
GST_REGISTRY_1_0='/mnt/flash/data/gst_1_0_registry.arm.bin'
GST_REGISTRY_UPDATE='no'
HISTFILE='/home/root/.ash_history'
HISTFILESIZE='1000'
HISTSIZE='1000'
HOME='/home/root'
HOOK_SEGV='NO'
HOOK_THR='NO'
HOSTNAME='LGwebOSTV'
IFS='
'
INITSCRIPTS='webos'
INPUTRC='/etc/inputrc'
IS_NFS='NO'
IS_SNAP='YES'
IS_SNAP_PROFILE='NO'
KDRV_DIR='/mnt/lg/res/lglib/kdrv'
KLOG='/dev/kmsg'
LD_LIBRARY_PATH='/mnt/bsppart/bsp/lib:/mnt/bsppart/bsp/usr/lib:/mnt/license/usr/                                                                                                                                                             lib:/home/root/lib'
LGAPP_DIR='/mnt/lg/lgapp'
LINENO=''
LOAD_DSYM='1'
LOAD_SYM='2'
LOGNAME='root'
LOG_CALLER='NO'
LOG_LEVEL='0'
LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:                                                                                                                                                             cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31                                                                                                                                                             :*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:                                                                                                                                                             *.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.png=01;35:*.gif=01;35:*.bmp=0                                                                                                                                                             1;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.t                                                                                                                                                             if=01;35:*.tiff=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;3                                                                                                                                                             5:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:'
OPTIND='1'
OSAMEM_SIZE='0x200000'
PAGER='/bin/more '
PATH='/usr/sbin:/usr/bin:/sbin:/bin:/home/root/bin'
PPID='2647'
PS1='[\u@\h \W]\$ '
PS2='> '
PS4='+ '
PWD='/home/root'
QML2_IMPORT_PATH='/usr/lib/qt5/qml'
QMLSCENE_DEVICE='customcontext'
QML_DISABLE_DISK_CACHE='1'
QSG_PROGRAM_BINARY_STORE='/var/cache/qsg-shader-cache'
QT_HARFBUZZ='new'
QT_IM_MODULE='wayland'
QT_QPA_FONTDIR='/usr/share/fonts'
QT_QPA_PLATFORM='wayland'
QT_VER='qt5'
QT_WAYLAND_DISABLE_WINDOWDECORATION='1'
QT_WAYLAND_HARDWARE_INTEGRATION='wayland-egl'
QT_WAYLAND_SHELL_INTEGRATION='webos'
QT_WAYLAND_XKB_RULE_NAMES='evdev:lgwebostv:us::'
ROOTFS_READ_ONLY='no'
RWMOUNT_FLAG='/tmp/mount-readwrite.conf.done'
SDL_VIDEODRIVER='wayland'
SDP_SYS_PATH='/mnt/cache/sdp'
SHELL='/bin/sh'
SHLVL='1'
SNAP_FLOCK='/tmp/snapshot_flock'
SSH_CLIENT='10.0.0.104 63639 22'
SSH_CONNECTION='10.0.0.104 63639 10.0.0.144 22'
SSH_TTY='/dev/pts/2'
SULOGIN='no'
SYSTEMD_ENV='APPFRWK_MASK_PATH=/mnt/lg/cmn_data/appfrwk_mask
ATTR_FORCE_SCHEDNORMAL=YES
COMPONENTS_PATH=/mnt/lg/res/lglib/openmax
CRASH_REPORT=YES
DBGFRWK_SYSLOG=GLOBAL
DEBUG_STATUS=3
DEFAULT_WORKINGSET=20480
DELAYLOGIN=no
EDITMOTD=no
ENABLE_ROOTFS_FSCK=no
FSCKFIX=yes
GDB_ROOT=$'"'"'$HOME'"'"'
GIO_EXTRA_MODULES=/usr/lib/gio/modules
GLIBC_BACKTRACE=YES
GST_PLUGIN_PATH=/usr/lib/gstreamer-0.10
GST_PLUGIN_PATH_1_0=/usr/lib/gstreamer-1.0:/mnt/lg/res/lglib/gstreamer-1.0
GST_PLUGIN_SCANNER=/usr/bin/gst-plugin-scanner
GST_PLUGIN_SCANNER_1_0=/usr/libexec/gstreamer-1.0/gst-plugin-scanner
GST_REGISTRY=/mnt/flash/data/gst_registry.arm.bin
GST_REGISTRY_1_0=/mnt/flash/data/gst_1_0_registry.arm.bin
GST_REGISTRY_UPDATE=no
HOME=/home/root
HOOK_SEGV=NO
HOOK_THR=NO
INITSCRIPTS=webos
IS_NFS=NO
IS_SNAP=YES
IS_SNAP_PROFILE=NO
KDRV_DIR=/mnt/lg/res/lglib/kdrv
KLOG=/dev/kmsg
LD_LIBRARY_PATH=/mnt/bsppart/bsp/lib:/mnt/bsppart/bsp/usr/lib:/mnt/license/usr/l                                                                                                                                                             ib
LGAPP_DIR=/mnt/lg/lgapp
LOAD_DSYM=1
LOAD_SYM=2
LOG_CALLER=NO
LOG_LEVEL=0
OSAMEM_SIZE=0x200000
PATH=/mnt/bsppart/bsp/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin
QML2_IMPORT_PATH=/usr/lib/qt5/qml
QMLSCENE_DEVICE=customcontext
QML_DISABLE_DISK_CACHE=1
QSG_PROGRAM_BINARY_STORE=/var/cache/qsg-shader-cache
QT_HARFBUZZ=new
QT_IM_MODULE=wayland
QT_QPA_FONTDIR=/usr/share/fonts
QT_QPA_PLATFORM=wayland
QT_VER=qt5
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_WAYLAND_HARDWARE_INTEGRATION=wayland-egl
QT_WAYLAND_SHELL_INTEGRATION=webos
QT_WAYLAND_XKB_RULE_NAMES=evdev:lgwebostv:us::
ROOTFS_READ_ONLY=no
RWMOUNT_FLAG=/tmp/mount-readwrite.conf.done
SDL_VIDEODRIVER=wayland
SDP_SYS_PATH=/mnt/cache/sdp
SNAP_FLOCK=/tmp/snapshot_flock
SULOGIN=no
TERM=linux
TMPTIME=0
USE_OSAMM=0
VERBOSE=no
VOLATILE_ENABLE_CACHE=yes
WEBAPPFACTORY=netcast:hbbtv
WEBOS_GL_DISABLE_THREADED_RENDERING=1
XDG_DIR=/tmp/xdg
XDG_RUNTIME_DIR=/tmp/xdg'
TERM='linux'
TMPTIME='0'
USER='root'
USE_OSAMM='0'
VERBOSE='no'
VOLATILE_ENABLE_CACHE='yes'
WEBAPPFACTORY='netcast:hbbtv'
WEBOS_GL_DISABLE_THREADED_RENDERING='1'
XDG_DIR='/tmp/xdg'
XDG_RUNTIME_DIR='/tmp/xdg'
```
Are you actually trying to run the script from an ssh session, or a simple telnet session, because I think this could explain the difference (with only ssh providing a more complete shell environment for the script to run properly).

**Comment by kshpits** [comment] 2023-02-13 16:35
You right, it was from telnet session. Here are variables from ssh session.
```
root@LGwebOSTV:~# set
APPFRWK_MASK_PATH='/mnt/lg/cmn_data/appfrwk_mask'
ATTR_FORCE_SCHEDNORMAL='YES'
COMPONENTS_PATH='/mnt/lg/res/lglib/openmax'
CRASH_REPORT='YES'
DBGFRWK_SYSLOG='GLOBAL'
DEBUG_STATUS='5'
DEFAULT_WORKINGSET='20480'
DELAYLOGIN='no'
EDITMOTD='no'
EDITOR='vi'
ENABLE_ROOTFS_FSCK='no'
FSCKFIX='yes'
GDB_ROOT='$'"'"'$HOME'"'"
GIO_EXTRA_MODULES='/usr/lib/gio/modules'
GLIBC_BACKTRACE='YES'
GST_PLUGIN_PATH='/usr/lib/gstreamer-0.10'
GST_PLUGIN_PATH_1_0='/usr/lib/gstreamer-1.0:/mnt/lg/res/lglib/gstreamer-1.0'
GST_PLUGIN_SCANNER='/usr/bin/gst-plugin-scanner'
GST_PLUGIN_SCANNER_1_0='/usr/libexec/gstreamer-1.0/gst-plugin-scanner'
GST_REGISTRY='/mnt/flash/data/gst_registry.arm.bin'
GST_REGISTRY_1_0='/mnt/flash/data/gst_1_0_registry.arm.bin'
GST_REGISTRY_UPDATE='no'
HISTFILE='/home/root/.ash_history'
HOME='/home/root'
HOOK_SEGV='NO'
HOOK_THR='NO'
HOSTNAME='LGwebOSTV'
IFS='
'
INITSCRIPTS='webos'
IS_NFS='NO'
IS_SNAP='YES'
IS_SNAP_PROFILE='NO'
KDRV_DIR='/mnt/lg/res/lglib/kdrv'
KLOG='/dev/kmsg'
LANG='C'
LD_LIBRARY_PATH='/mnt/bsppart/bsp/lib:/mnt/bsppart/bsp/usr/lib:/mnt/license/usr/                                                                                                             lib'
LGAPP_DIR='/mnt/lg/lgapp'
LINENO=''
LOAD_DSYM='1'
LOAD_SYM='2'
LOGNAME='root'
LOG_CALLER='NO'
LOG_LEVEL='0'
OPTIND='1'
OSAMEM_SIZE='0x200000'
PATH='/mnt/bsppart/bsp/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PPID='9131'
PS1='\u@\h:\w\$ '
PS2='> '
PS4='+ '
PWD='/home/root'
QML2_IMPORT_PATH='/usr/lib/qt5/qml'
QMLSCENE_DEVICE='customcontext'
QML_DISABLE_DISK_CACHE='1'
QSG_PROGRAM_BINARY_STORE='/var/cache/qsg-shader-cache'
QT_HARFBUZZ='new'
QT_IM_MODULE='wayland'
QT_QPA_FONTDIR='/usr/share/fonts'
QT_QPA_PLATFORM='wayland'
QT_VER='qt5'
QT_WAYLAND_DISABLE_WINDOWDECORATION='1'
QT_WAYLAND_HARDWARE_INTEGRATION='wayland-egl'
QT_WAYLAND_SHELL_INTEGRATION='webos'
QT_WAYLAND_XKB_RULE_NAMES='evdev:lgwebostv:us::'
ROOTFS_READ_ONLY='no'
RWMOUNT_FLAG='/tmp/mount-readwrite.conf.done'
SDL_VIDEODRIVER='wayland'
SDP_SYS_PATH='/mnt/cache/sdp'
SHELL='/bin/sh'
SHLVL='1'
SNAP_FLOCK='/tmp/snapshot_flock'
SSH_CLIENT='192.168.1.13 12211 22'
SSH_CONNECTION='192.168.1.13 12211 192.168.1.116 22'
SSH_TTY='/dev/pts/3'
SULOGIN='no'
SYSTEMD_ENV='APPFRWK_MASK_PATH=/mnt/lg/cmn_data/appfrwk_mask
ATTR_FORCE_SCHEDNORMAL=YES
COMPONENTS_PATH=/mnt/lg/res/lglib/openmax
CRASH_REPORT=YES
DBGFRWK_SYSLOG=GLOBAL
DELAYLOGIN=no
EDITMOTD=no
ENABLE_ROOTFS_FSCK=no
FSCKFIX=yes
GDB_ROOT=$'"'"'$HOME'"'"'
GIO_EXTRA_MODULES=/usr/lib/gio/modules
GLIBC_BACKTRACE=YES
GST_PLUGIN_PATH=/usr/lib/gstreamer-0.10
GST_PLUGIN_PATH_1_0=/usr/lib/gstreamer-1.0:/mnt/lg/res/lglib/gstreamer-1.0
GST_PLUGIN_SCANNER=/usr/bin/gst-plugin-scanner
GST_PLUGIN_SCANNER_1_0=/usr/libexec/gstreamer-1.0/gst-plugin-scanner
GST_REGISTRY=/mnt/flash/data/gst_registry.arm.bin
GST_REGISTRY_1_0=/mnt/flash/data/gst_1_0_registry.arm.bin
GST_REGISTRY_UPDATE=no
HOME=/home/root
HOOK_SEGV=NO
HOOK_THR=NO
INITSCRIPTS=webos
KDRV_DIR=/mnt/lg/res/lglib/kdrv
KLOG=/dev/kmsg
LANG=C
LD_LIBRARY_PATH=/mnt/bsppart/bsp/lib:/mnt/bsppart/bsp/usr/lib:/mnt/license/usr/l                                                                                                             ib
LGAPP_DIR=/mnt/lg/lgapp
LOAD_DSYM=1
LOAD_SYM=2
LOG_CALLER=NO
OSAMEM_SIZE=0x200000
PATH=/mnt/bsppart/bsp/usr/bin:/usr/sbin:/usr/bin:/sbin:/bin
QML2_IMPORT_PATH=/usr/lib/qt5/qml
QMLSCENE_DEVICE=customcontext
QML_DISABLE_DISK_CACHE=1
QSG_PROGRAM_BINARY_STORE=/var/cache/qsg-shader-cache
QT_HARFBUZZ=new
QT_IM_MODULE=wayland
QT_QPA_FONTDIR=/usr/share/fonts
QT_QPA_PLATFORM=wayland
QT_VER=qt5
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
QT_WAYLAND_HARDWARE_INTEGRATION=wayland-egl
QT_WAYLAND_SHELL_INTEGRATION=webos
QT_WAYLAND_XKB_RULE_NAMES=evdev:lgwebostv:us::
ROOTFS_READ_ONLY=no
RWMOUNT_FLAG=/tmp/mount-readwrite.conf.done
SDL_VIDEODRIVER=wayland
SDP_SYS_PATH=/mnt/cache/sdp
SNAP_FLOCK=/tmp/snapshot_flock
SULOGIN=no
TERM=linux
TMPTIME=0
USE_OSAMM=0
VERBOSE=no
VOLATILE_ENABLE_CACHE=yes
WEBAPPFACTORY=netcast:hbbtv
WEBOS_GL_DISABLE_THREADED_RENDERING=1
XDG_DIR=/tmp/xdg
XDG_RUNTIME_DIR=/tmp/xdg
DEBUG_STATUS=5
DEFAULT_WORKINGSET=20480
IS_NFS=NO
IS_SNAP=YES
IS_SNAP_PROFILE=NO
LOG_LEVEL=0
USE_EFS_SWAP=YES'
TERM='linux'
TMPTIME='0'
USER='root'
USE_EFS_SWAP='YES'
USE_OSAMM='0'
VERBOSE='no'
VOLATILE_ENABLE_CACHE='yes'
WEBAPPFACTORY='netcast:hbbtv'
WEBOS_GL_DISABLE_THREADED_RENDERING='1'
XDG_DIR='/tmp/xdg'
XDG_RUNTIME_DIR='/tmp/xdg'
_='022'
```

**Comment by pbatard** [comment] 2023-02-13 16:36
Then please try to run the script again from ssh, because I can see that you do have `$GST_REGISTRY_1_0` defined there.

**Comment by kshpits** [comment] 2023-02-13 16:38
Yes it worked, at least output shows that:

```
This installer was designed specifically for LG OLED CX TVs running
webOS 5.x with Gstreamer 1.14.4. However, you are trying run it on a(n)
OLED-A55 TV with webOS 7.3.0 and GStreamer 1.18.2.

While installing this software on an incompatible platform should not
cause irreversible damage, if you choose to proceed, you do acknowlegde
that, because you are not using the relevant target system:
1. The software may not work as expected, it at all.
2. You may lose existing features and/or functionality.
3. The entire responsibility for trying this software on an unsupported
   platform lies entirely with you.

Do you wish to proceed? [y/N] y
Installing /var/lib/webosbrew/init.d/restore_dts
Running /var/lib/webosbrew/init.d/restore_dts
Installing /usr/lib/gstreamer-1.0/libgstmatroska.so override
Installing /usr/lib/gstreamer-1.0/libgstlibav.so override
Installing /mnt/flash/data/gst_1_0_registry.arm.bin override
>> [gst.tracer][INFO ][default] [ 9348][  0x799020] cooltracer registered
Installing /etc/gst/gstcool.conf override
DTS playback has been permanently re-enabled - Enjoy!
```

**Comment by pbatard** [comment] 2023-02-13 16:41
Okay, then please try to play a `.mkv` with a DTS track and report if you get audio output (being mindful that it will usually fail the first time around, but it should work the second time).

**Comment by kshpits** [comment] 2023-02-13 16:46
Test MKV with DTS played well, thanks for your work and help switching to ssh!

**Comment by pbatard** [comment] 2023-02-13 16:48
Great! I will close this issue now, and I will also add a note to the script to mention that *ssh* should be used over *telnet* when `$GST_REGISTRY_1_0` cannot be found.

**Closed as completed by pbatard** 2023-02-13 16:48 UTC
